### ISSUE TITLE
Wrapper ignored in fullpage view

### ISSUE THREAD

**Issue by felixranesberger** [scheibome/kss-scheibo#41]
When defining a `wrapper` for a styleguide item, the wrapper is not present in the fullpage view. 

```scss
/*
Frame Startpage

Markup: templates/output/05-objects/frame.html

Wrapper:
<div class="page--startpage>
  <wrapper-content/>
</div>

Styleguide 3.1
*/
```

**Comment by scheibome** [comment]
This is not a bug but a feature.

The wrapper is there in the list view, e.g. to set an absolute positioned element to an element which has position:relative, so that the list view is not destroyed.

**Comment by felixranesberger** [comment]
I wanted to use the wrapper for content elements, that are only styled for the startpage. 
As the content elements are startpage only I need the `page--startpage` wrapper class for the styling to work correctly but are not part of the component itself.

I would think that the wrapper is used for this and that you would fix stuff like you mentioned by resetting it with something like this:


```scss
.top-bar {
  position: fixed;

  // disable fixed position when in styleguide, as it breaks the layout
  .kss-section & {
    position: relative;
  }
}
```

## Important side note:
The current functionality has a bug in it, where the modifier fullpage preview gets the wrapper class, but the default view doesn't. This means that the wrapper class is included in the modifier fullpage, but not in the default fullpage. So in either case we would need to fix this issue.

### Default call
look for `''` after `...referenceURI 'default'`
https://github.com/scheibome/kss-scheibo/blob/8fffada1c05e309a07c1066a43c10310836a55fc/kss_styleguide/scheibo-template/index.hbs#L182

### Modifier call
(look for `@key ../wrapper`)
https://github.com/scheibome/kss-scheibo/blob/8fffada1c05e309a07c1066a43c10310836a55fc/kss_styleguide/scheibo-template/index.hbs#L204
